# Generated by Django 2.2 on 2023-01-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dob', models.DateField(max_length=8)),
                ('inClass', models.TextField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
