# Generated by Django 2.2 on 2023-01-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageData', '0002_auto_20230101_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
