# Generated by Django 2.2 on 2023-01-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageData', '0004_auto_20230102_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sample',
            field=models.IntegerField(default=0, verbose_name='Number of Sample'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Employee Name'),
        ),
    ]
