# Generated by Django 2.2 on 2023-01-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageData', '0006_auto_20230102_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='finger_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_data')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageData.Employee')),
            ],
        ),
    ]
